local putil = require('plenary.async.util')
local async = require('plenary.async')
local ft = require('plink')

async.run(function()
  ft.search('h')
  putil.sleep(100)
  ft.search('ha')
  putil.sleep(100)
  ft.search('har')
  putil.sleep(100)
  ft.search('harp')
  putil.sleep(600)
  ft.search('harpoo')
end)
