return {
  star = '',
  star_fancy = '⭐',
  checkbox_filled = '',
  unchecked_filled = '',
  unchecked = '',
  checkbox = '',
  select_arrow = '',
  github = '',
  package = '',
  package_fancy = '📦',
  list = '',
  flame = '',
  url = '',
  description = '',
  document = '',
  text = '',
  lightning = '',
  lightning_fancy = '⚡️',
  sparkles = '',
  sparkles_fancy = '✨',
  rocket = '🚀',
}
